- src: siamaksade.openshift_sonatype_nexus
  version: ocp-3.11
  name: openshift_sonatype_nexus

- src: siamaksade.openshift_gogs
  version: ocp-3.11
  name: openshift_gogs

- src: siamaksade.openshift_workshopper
  version: ocp-3.11
  name: openshift_workshopper

- src: mcouliba.openshift_codeready_workspaces
  version: 1.0.0
  name: openshift_codeready_workspaces